### ISSUE TITLE
figure out what needs to be refunded and automate

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad#45]
make refund function, allow user to trigger refund: http://{assembler}/return/{walletAddress}/{p2s}

store p2s with transaction

/api/assembler or other function to allow assembler to stay hidden

http://38.15.40.14:8888/return/9eqJkWbGaz3mCyDBpaGdo42sHog9AkhemDvtJAqkPuw1YDHxcUs/j2KbCd42Wt5suULR2pS66MQ2x2aoeKKH7bP3d7QouMd5fkcnhZH8DEbVBVQoYv4Yap1owgsMJjsjFtw8WRkMKzXFRPqftWwA8qQKeAwa5LuzXWZDPytKzLZHzX53GcJzbJ9NvT5gN414XaZAsYuVtHXy4eRmpfNiZ6mqsjudFGLXkYPP1y9St2efrv5ybhufTCkg1HVto6HHq6aD8BuBqbmJtgNCthnEKwCKiWdtANEY5WZPPSdQPbDemYXysKvKvxtqWiJHaVJBjx1q46VEGsjb3sKwspWsHroJRsWkQ69mzoibUsvFrvFKBLNeKq4wX4YXbZP9MDoTEuXnS6V9TCGpBB6CyhAXezafcMpsatbuZ9jtEXDScEUr5A9X92xrjcuyiXvcLUmNsBL9oRcaDDHeGeH6e6jRmVuSF41JxNTLBq96kYi3

**Comment by esot321c** [comment]
Will build front-end form
