### ISSUE TITLE
Staking contracts

### ISSUE THREAD

**Issue by Luivatra** [ergo-pad/ergopad#63]
Write the staking contracts for ErgoPads staking setup.

- [x] Research ErgoProfitSharingDapp
- [x] Initial draft of contracts
- [x] Finalize contracts
- [x] Test contracts
- [x] Review contracts

**Comment by esot321c** [comment]
When we get back to this, can we have an ability to stake something and received different assets back. Like somebody could add any asset to the staking contract along with the distribution time-frame and that would be included in the distribution?

**Comment by esot321c** [comment]
Please add a way to have distribution be split between the staker and some other wallet. For example, if we wanted to take 1% of staking rewards to the ergopad treasury, we could toggle the staking contract to allow that at initiation.
