### ISSUE TITLE
whitelist values for sql

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad#80]
- [x] name: presale-whitelist-20220115
- [ ] pretty name: Pre-sale whitelist - Jan 15, 2022
- [x] tokens: 20M, 2 decimals
- [x] sale price: .03
- [x] total whitelist: $600k sigusd
- [x] additional/waitlist: $600k sigusd (1.2M total)
- [x] start: 1/15/2022 5p UTC

**Comment by esot321c** [comment]
What do you want for "pretty name"?

**Comment by vikingphoenix** [comment]
presale-202201 or pretty name "Pre-Sale Jan. 2022"...or whatever lol, the first name will be unique but the pretty name can be anything
