### ISSUE TITLE
Enable historical chart

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad#90]
Let’s start tracking token data and price data in celery so that all portfolios can display a historic chart. It doesn’t have to get super complicated, maybe just a line chart where users can separate by assets or show overall. 

A stacked area chart will be perfect for this display. The Y-axis will be value, and the X-axis will be time. Users can click individual assets to include or remove them. Users can switch between 1 day, 1 week, 1 month, and 1 year time-frame perhaps? Depends how long we plan to track, and the granularity.

**Comment by vikingphoenix** [comment]
@noob77777 the, "aggregator" is currently running on alpha and storing values in various tables on the SQL server, hello database.

This chart should also track token prices once they come in from ergodex, but for now we have ergo and sigusd/sigrsv.

**Comment by noob77777** [comment]
For portfolio value we need history of what quantity of each token the user had at each point of time. How are we planning to do that?

**Comment by noob77777** [comment]
do we want ```portfolio value v time``` or ```erg/usd v time```

**Comment by esot321c** [comment]
> quantity

You can run through their previous transactions and get an accurate time stamp based on when the tokens were transferred into the wallet. It might take some figuring out how to sort the data

**Comment by noob77777** [comment]
https://docs.google.com/document/d/1BtK2sRDYTqXCmssc3WXdDMn8mE51vCmH2CJIxpzXjlE
